apiVersion: apps/v1
kind: Deployment
metadata:
  name: topcoins-service-deployment
  labels:
    app: topcoins-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topcoins-service
  template:
    metadata:
      labels:
        app: topcoins-service
    spec:
      containers:
        - name: topcoins-service
          image: docker.io/library/aab
          imagePullPolicy: Never
          ports:
            - containerPort: 5001