FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the entire front-end source code
COPY . .

CMD [ "node", "./index.js" ]
